language: python
sudo: false
python:
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  - "nightly"
install:
  - pip install -e .[testing]
  - pip install dictknife[load]
  - pip install cookiecutter  # for examples/extensions
script:
  - python setup.py test
  - make ci
