from kamidana.loader import TemplateLoader


class WithHeaderLoader(TemplateLoader):
    def load(self, filename):
        buf = []
        buf.append("# this file is auto generated by {!r}.\n\n".format(filename))
        r, filename, _ = super().load(filename)
        buf.append(r)
        return "".join(buf)
